version: "3.7"

services:
  controlnode:
    build:
      context: control-node/
      args:
        ANSIBLE_VERSION: ${ANSIBLE_VERSION}
    working_dir: /code/playbook-example
    restart: 'no'
    user: '0'
    volumes:
      - secrets:/secrets
      - ansible-roles:/roles
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: sh entrypoint
    env_file:
    - .env
  managedhost-alpine:
    build: 
      context: managed-host/alpine/
      target: alpine-sshd
    restart: unless-stopped
    # volumes:
    #   - secrets/id_rsa.pub:/root/.ssh/authorized_keys
    ports:
      - 3001:3000
#      - 2222:22
    environment:
      - SSH_ENABLE_ROOT=true
      # - SSH_USERS="admin:1000:1000"
    deploy:
      replicas: 3
  managedhost-redhat-base: &systemdbase
    image: hello-world
    restart: 'no'
    tmpfs:
    - /run
    - /run/lock
    - /var/cache
    - /tmp
    cap_add:
    - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true

  managedhost-rhel8:
    <<: *systemdbase
    container_name: rhel8-example-com
    # build: managed-host/rhel8/
    image: abdennour/rhel:8-ssh
    restart: unless-stopped
    ports:
      - 8081:80 # playbook will run nginx


  managedhost-centos7:
    <<: *systemdbase
    container_name: centos7-example-com
    image: centos/systemd
    restart: unless-stopped
    ports:
      - 8082:80 # playbook will run nginx
  managedhost-alpine-systemd:
    container_name: alpinesystemd-example-com
    build:
      context: managed-host/alpine/
      target: alpine-systemd
    restart: unless-stopped
    ports:
      - 8083:80

volumes:
  secrets:
  ansible-roles:

