version: "3.7"

services:
  controlnode:
    build: control-node/
    image: ansible:controlnode
    working_dir: /playbook
    command: 'tail -f /dev/null'
    volumes:
      - ./secrets:/secrets
      - ./playbook-example:/playbook
      - /var/run/docker.sock:/var/run/docker.sock:ro
  managedhost-alpine:
    container_name: ansible-lab-managedhost-alpine
    build: 
      context: managed-host/alpine/
      target: alpine-sshd
    restart: unless-stopped
    volumes:
      - ./secrets/id_rsa.pub:/root/.ssh/authorized_keys
    ports:
      - 3001:3000
#      - 2222:22
    environment:
      - SSH_ENABLE_ROOT=true
      # - SSH_USERS="admin:1000:1000"
    deploy:
      replicas: 3
  managedhost-redhat-base: &systemdbase
    image: hello-world
    restart: 'no'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true

  managedhost-rhel8:
    <<: *systemdbase
    container_name: ansible-lab-managedhost-rhel8
    build: managed-host/rhel8/
    restart: unless-stopped
    ports:
      - 8081:80 # playbook will run nginx


  managedhost-centos7:
    <<: *systemdbase
    container_name: ansible-lab-managedhost-centos7
    image: centos/systemd
    restart: unless-stopped
    ports:
      - 8082:80 # playbook will run nginx
  managedhost-alpine-systemd:
    container_name: ansible-lab-managedhost-alpine-systemd
    build:
      context: managed-host/alpine/
      target: alpine-systemd
    restart: unless-stopped
    ports:
      - 8083:80



